name: test

on: [push]

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - run: make install
        id: install
      - run: |
          forge --version
          forge build --sizes
        id: build
      - run: make test
        id: test
